### ISSUE TITLE
Create backup files that can be loaded into signal mobile?

### ISSUE THREAD

**Issue by aleqsio** [tbvdm/sigtop#3] opened 2021-11-23 14:38 UTC
I'm wondering if you looked into rearchiving the messages and attachments into a binary file readable by the signal android or ios apps - this way you would be able to reload the messages on mobile if you loose your previous mobile app but retain access to a desktop app?

I'd imagine existing signal open source code for archiving could be used, but there might be some complex wiring necessary.

**Comment by tbvdm** [comment] 2021-11-24 15:20
I've considered it, and it would certainly be a very useful feature. Unfortunately, it's not simply a matter of rearranging data into a different format. Such a feature would require a lot of testing before you can be reasonably sure that it works as intended and won't do more harm than good. I'm worried about subtle problems with the generated backups that, sooner or later, will cause data loss or other problems in Signal. Moreover, the Signal apps are being actively developed and things continuously change. So even if the feature would work fine today, it might break tomorrow.

**Comment by tbvdm** [comment] 2022-01-10 19:08
I think we can close this. If not, feel free to reopen.

**Closed by tbvdm** 2022-01-10 19:08 UTC
